### PR TITLE
Changes and new bug report/feature suggestion section.

### PR DESCRIPTION
**Pull request by Nifty-Neutron**
I improved some things (in my opinion) and added a bug report/feature suggestion section(mostly linking to the issue template).

### CODE REVIEW

**Comment by realjackasterisk** [comment]
i just randomly decide to check this repo and i see a pull request i NEVER got any notification about. thanks github!

**Comment by realjackasterisk** [comment]
alright i looked at the updated file. few things i wanna mention/ask:

1. is there a specific reason for adding the 4 dividing lines around the optifine.net links? feels like it's a bit much.
2. there are several issues with grammar and structure at the final section of the text. for example, why is there a sudden line break in the middle of the very last sentence?
3. why link the raw issue template used by github? you can easily use the actual bug report link: ```https://github.com/sp614x/optifine/issues/new?assignees=&labels=&template=bug_report.md&title=%5BCategory%5D+Short+description```

**Comment by Nifty-Neutron** [comment]
OK let's start
1-the "and" looked off-center for me and by adding these lines it felt centered and looked cool for me,I can change it if you want.
2-English isn't my native language and I didn't check the grammar much,I will look into it later.
3-I'm new to github and git,I have a lot to learn.
Thanks for reading,
have a nice day.

**Comment by Nifty-Neutron** [comment]
also for the line break I was just learning and testing and left it as it is,
I will change it.

**Comment by Nifty-Neutron** [comment]
Also,sending the user to https://github.com/sp614x/optifine/issues/new/choose
feels better,doesn't it.

**Comment by realjackasterisk** [comment]
I might have an idea to fix the text centering issue.

I.... don't really know how to go about this, so I'll just merge it here and make some edits myself.

**Pull request merged**
